# Personal Details
EXP_INTERN_CHOICES=(('YES',"YES"),("NO","NO"))
GENDER_CHOICES=(("MALE","MALE"),("FEMALE","FEMALE"),("OTHERS","OTHERS"))
# ActivityAchievementDetails
ACTIVITY_ACHIEVEMENTS=(("ACTIVITY","ACTIVITY"),("ACHIEVEMENT","ACHIEVEMENT"))
# Training Details
TRAINING_CHOICES=(('ONLINE','ONLINE'),('OFFLINE',"OFFLINE"))
# Experience Details
EXPERIENCE_CHOICES=(('WORK FROM HOME','WORK FROM HOME'),('PART TIME','PART TIME'),('FULL TIME','FULL TIME'))
# Internship Details
INTERNSHIP_CHOICES=(("OFFLINE",'OFFLINE'),('PART TIME',"PART TIME"),("ONLINE","ONLINE"))
# Experience Choices
EXPERIENCE_CHOICES=(("YES","YES"),("NO","NO"))
# Internship Choices
INTERNSHIP_CHOICES=(("YES","YES"),("NO","NO"))
# Certification Details
TRAINING_CHOICES=(('ONLINE','ONLINE'),('OFFLINE',"OFFLINE"))
# EDUCATION TYPE
EDUCATION_CHOICES=(('SCHOOL','SCHOOL'),("HIGH SCHOOL","HIGH SCHOOL"),('UNIVERSITY',"UNIVERSITY"),("HIGHER STUDIES","HIGHER STUDIES"))

