from django.urls import path
from MyResumeBuilder import settings
from django.conf.urls.static import static
from . import views
app_name='resumes'
urlpatterns=[
    path('register/', views.register, name='register'),
    path('login/', views.SignIn, name='login'),
    path('logout/',views.signout, name='LogOut'),
    path('',views.HomeView,name='Home'),
    path('AboutUs/',views.AboutView,name='AboutView'),
    path('ResumePoints/',views.ResumePointView,name='ResumePoints'),
    path('CheckExperience/',views.CheckExperienceDetailView,name='CheckExperiences'),
    path('ExperienceResumesList/',views.ExperienceResumesListView,name='Experience-Resumes'),
    path('NoExperienceResumesList/',views.NoExperienceResumesListView,name='NoExperience-Resumes'),
    # Show All Experience Related Details
    path('Experience/ShowDetails/',views.ExpShowDetailView,name='Exp-ShowDetails'),
    path('NoExperience/ShowDetails/',views.NoExpShowDetailView,name='NoExp-ShowDetails'),
    # Experience Resume Views
    path('Experience/Resume1/',views.ExperienceResume1view,name='Exp-Resume1'),
    path('Experience/Resume2/PDF/',views.GeneratePDF2,name='Exp-Resume2'),
    path('Experience/Resume1/PDF/',views.ExpResume1PDF,name='Exp-Resume1-Pdf'),
    path('Experience/Resume1/PDFView/',views.GeneratePdf.as_view(),name='Exp-Resume1-Pdf'),
    path('Experience/Resume2/',views.ExperienceResume2view,name='Exp-Resume2'),
    path('Experience/Resume3/',views.ExperienceResume3view,name='Exp-Resume3'),
    path('Experience/Resume3/PDFView/',views.GenerateRes3Pdf.as_view(),name='GenRes3'),
    path('Experience/Resume4/',views.ExperienceResume4view,name='Exp-Resume4'),
    path('Experience/Resume5/',views.ExperienceResume5view,name='Exp-Resume5'),
    # No Experience Resume Views
    path('NoExperience/Resume1/',views.NoExperienceResume1View,name='NoExp-Resume1'),
    path('NoExperience/Resume2/',views.NoExperienceResume2View,name='NoExp-Resume2'),
    path('NoExperience/Resume3/',views.NoExperienceResume3View,name='NoExp-Resume3'),
    path('NoExperience/Resume4/',views.NoExperienceResume4View,name='NoExp-Resume4'),
    # Experience Path Links
    path('Experience/ContactDetails/',views.ExpContactDetailView,name='Exp-ContactDetails'),
    path('Experience/PersonalDetails/',views.ExpPersonalDetailView,name='Exp-PersonalDetails'),
    path('Experience/LanguageDetails/',views.ExpLanguageDetailView,name='Exp-LanguageDetails'),
    path('Experience/SocialMediaDetails/',views.ExpSocialMediaLinkView,name='Exp-SocialMediaDetails'),
    path('Experience/ActivityAchievementDetails/',views.ExpAchievementsOrActivitiesDetailView,name='Exp-ActivityAchievements'),
    path('Experience/SkillDetails/',views.ExpSkillDetailView,name='Exp-SkillDetails'),
    path('Experience/InterestDetails/',views.ExpInterestDetailView,name='Exp-InterestDetails'),
    path('Experience/SoftSkillDetails/',views.ExpSoftSkillDetailView,name='Exp-SoftSkillDetails'),
    path('Experience/StrengthWeaknessDetails/',views.ExpStrengthWeaknessDetailView,name='Exp-StrengthWeakness'),
    path('Experience/HobbieDetails/',views.ExpHobbieDetailView,name='Exp-HobbieDetails'),
    path('Experience/ProjectDetails/',views.ExpProjectDetailView,name='Exp-ProjectDetails'),
    path('Experience/SummaryDetails/',views.ExpSummaryDetailView,name='Exp-SummaryDetails'),
    path('Experience/EducationDetails/',views.ExpEducationDetailView,name='Exp-EducationDetails'),
    path('Experience/CertificationDetails/',views.ExpCertificationDetailView,name='Exp-CertificationDetails'),
    path('Experience/TrainingDetails/',views.ExpTrainingDetailView,name='Exp-TrainingDetails'),
    path('Experience/InternshipDetails/',views.ExpInternshipDetailView,name='Exp-InternshipDetails'),
    path('Experience/ExperienceDetails/',views.ExpExperienceDetailView,name='Exp-ExperienceDetails'),   
    # Add Experience Links
    path('Experience/EducationDetails/AddEducation/',views.ExpAddEducationDetailView,name='AddExpEducation'),
    path('Experience/SkillDetails/AddSkills/',views.ExpAddSkillDetailView,name='AddExpSkills'),
    path('Experience/SoftSkillDetails/AddSoftSkills/',views.ExpAddSoftSkillDetailView,name='AddExpSoftSkills'),
    path('Experience/HobbieDetails/AddHobbies/',views.ExpAddHobbieDetailView,name='AddExpHobbies'),
    path('Experience/SocialMediaDetails/AddSocialMediaDetails/',views.ExpAddSocialMediaDetailView,name='AddExpSocialMedia'),
    path('Experience/LanguageDetails/AddLanguageDetails/',views.ExpAddLanguageDetailView,name='AddExpLanguages'),
    path('Experience/ActivityAchievementDetails/AddActivityAchievements/',views.ExpAddActivityAchievementDetailView,name='AddExpActivityAchievements'),
    path('Experience/InterestDetails/AddInterestDetails',views.ExpAddInterestDetailView,name='AddExpInterests'),
    path('Experience/StrengthWeaknessDetails/AddStrengthWeakness/',views.ExpAddStrengthWeaknessDetailView,name='AddExpStrengthWeakness'),
    path('Experience/ProjectDetails/AddProjects/',views.ExpAddProjectDetailView,name='AddExpProjects'),
    path('Experience/TrainingDetails/AddTrainingDetails/',views.ExpAddTrainingDetailView,name='AddExpTrainingDetails'),
    path('Experience/CertificationDetails/AddCertifications/',views.ExpAddCertificationDetailView,name='AddExpCertifications'),
    path('Experience/InternshipDetails/AddInternships/',views.ExpAddInternshipDetailView,name='AddExpInternships'),
    path('Experience/ExperienceDetails/AddExperiences/',views.ExpAddExperienceDetailView,name='AddExpExperiences'),
# Add Detail Links
    
# NoExperience Links
    path('NoExperience/ContactDetails/',views.NoExpContactDetailView,name='NoExp-ContactDetails'),
    path('NoExperience/PersonalDetails/',views.NoExpPersonalDetailView,name='NoExp-PersonalDetails'),
    path('NoExperience/LanguageDetails/',views.NoExpLanguageDetailView,name='NoExp-LanguageDetails'),
    path('NoExperience/SocialMediaDetails/',views.NoExpSocialMediaLinkView,name='NoExp-SocialMediaDetails'),
    path('NoExperience/ActivityAchievementDetails/',views.NoExpAchievementsOrActivitiesDetailView,name='NoExp-ActivityAchievements'),
    path('NoExperience/SkillDetails/',views.NoExpSkillDetailView,name='NoExp-SkillDetails'),
    path('NoExperience/InterestDetails/',views.NoExpInterestDetailView,name='NoExp-InterestDetails'),
    path('NoExperience/SoftSkillDetails/',views.NoExpSoftSkillDetailView,name='NoExp-SoftSkillDetails'),
    path('NoExperience/StrengthWeaknessDetails/',views.NoExpStrengthWeaknessDetailView,name='NoExp-StrengthWeakness'),
    path('NoExperience/HobbieDetails/',views.NoExpHobbieDetailView,name='NoExp-HobbieDetails'),
    path('NoExperience/ProjectDetails/',views.NoExpProjectDetailView,name='NoExp-ProjectDetails'),
    path('NoExperience/SummaryDetails/',views.NoExpSummaryDetailView,name='NoExp-SummaryDetails'),
    path('NoExperience/EducationDetails/',views.NoExpEducationDetailView,name='NoExp-EducationDetails'),
    path('NoExperience/CertificationDetails/',views.NoExpCertificationDetailView,name='NoExp-CertificationDetails'),
    path('NoExperience/TrainingDetails/',views.NoExpTrainingDetailView,name='NoExp-TrainingDetails'),
# NoExperience Add Links
    path('NoExperience/EducationDetails/AddEducation/',views.NoExpAddEducationDetailView,name='AddNoExpEducation'),
    path('NoExperience/SkillDetails/AddSkills/',views.NoExpAddSkillDetailView,name='AddNoExpSkills'),
    path('NoExperience/SoftSkillDetails/AddSoftSkills/',views.NoExpAddSoftSkillDetailView,name='AddNoExpSoftSkills'),
    path('NoExperience/HobbieDetails/AddHobbies/',views.NoExpAddHobbieDetailView,name='AddNoExpHobbies'),
    path('NoExperience/SocialMediaDetails/AddSocialMediaDetails/',views.NoExpAddSocialMediaDetailView,name='AddNoExpSocialMedia'),
    path('NoExperience/LanguageDetails/AddLanguageDetails/',views.NoExpAddLanguageDetailView,name='AddNoExpLanguages'),
    path('NoExperience/ActivityAchievementDetails/AddActivityAchievements/',views.NoExpAddActivityAchievementDetailView,name='AddNoExpActivityAchievements'),
    path('NoExperience/InterestDetails/AddInterestDetails',views.NoExpAddInterestDetailView,name='AddNoExpInterests'),
    path('NoExperience/StrengthWeaknessDetails/AddStrengthWeakness/',views.NoExpAddStrengthWeaknessDetailView,name='AddNoExpStrengthWeakness'),
    path('NoExperience/ProjectDetails/AddProjects/',views.NoExpAddProjectDetailView,name='AddNoExpProjects'),
    path('NoExperience/TrainingDetails/AddTrainingDetails/',views.NoExpAddTrainingDetailView,name='AddNoExpTrainingDetails'),
    path('NoExperience/CertificationDetails/AddCertifications/',views.NoExpAddCertificationDetailView,name='AddNoExpCertifications'),
# Edit or Update Details
    path('Experience/ContactDetails/EditDetails/<int:c_id>/',views.EditExpContactDetailView,name='Edit-ExpContactDetails'),
    path('Experience/PersonalDetails/EditDetails/<int:p_id>/',views.EditExpPersonalDetailView,name='Edit-ExpPersonalDetails'),
    path('Experience/EducationDetails/EditDetails/<int:e_id>/',views.EditExpEducationDetailView,name='Edit-ExpEducationDetails'),
    path('Experience/LanguageDetails/EditDetails/<int:l_id>/',views.EditExpLanguageDetailView,name='Edit-ExpLanguageDetails'),
    path('Experience/SocialMediaDetails/EditDetails/<int:sm_id>/',views.EditExpSocialMediaDetailView,name='Edit-ExpSocialMediaDetails'),
    path('Experience/ActivityAchievementDetails/EditDetails/<int:aa_id>/',views.EditExpActivityAchievementDetailView,name='Edit-ExpActivityAchievements'),
    path('Experience/SkillDetails/EditDetails/<int:sk_id>/',views.EditExpSkillDetailView,name='Edit-ExpSkillDetails'),
    path('Experience/InterestDetails/EditDetails/<int:i_id>/',views.EditExpInterestDetailView,name='Edit-ExpInterestDetails'),
    path('Experience/SoftSkillDetails/EditDetails/<int:ss_id>/',views.EditExpSoftSkillDetailView,name='Edit-ExpSoftSkills'),
    path('Experience/StrengthWeaknessDetails/EditDetails/<int:sw_id>/',views.EditExpStrengthWeaknessDetailView,name='Edit-ExpStrengthWeakness'),
    path('Experience/HobbieDetails/EditDetails/<int:h_id>/',views.EditExpHobbieDetailView,name='Edit-ExpHobbies'),
    path('Experience/ProjectDetails/EditDetails/<int:p_id>/',views.EditExpProjectDetailView,name='Edit-ExpProjects'),
    path('Experience/SummaryDetails/EditDetails/<int:s_id>/',views.EditExpSummaryDetailView,name='Edit-ExpSummary'),
    path('Experience/TrainingDetails/EditDetails/<int:t_id>/',views.EditExpTrainingDetailView,name='Edit-ExpTrainingDetails'),
    path('Experience/CertificationDetails/EditDetails/<int:c_id>/',views.EditExpCertificationDetailView,name='Edit-ExpCertifications'),
    path('Experience/InternshipDetails/EditDetails/<int:in_id>/',views.EditExpInternshipDetailView,name='Edit-ExpInternships'),
    path('Experience/ExperienceDetails/EditDetails/<int:exp_id>/',views.EditExpExperienceDetailView,name='Edit-ExpExperiences'),
# No Experience or Update Details
    path('NoExperience/ContactDetails/EditDetails/<int:c_id>/',views.EditNoExpContactDetailView,name='Edit-NoExpContactDetails'),
    path('NoExperience/PersonalDetails/EditDetails/<int:p_id>/',views.EditNoExpPersonalDetailView,name='Edit-NoExpPersonalDetails'),
    path('NoExperience/EducationDetails/EditDetails/<int:e_id>/',views.EditNoExpEducationDetailView,name='Edit-NoExpEducationDetails'),
    path('NoExperience/LanguageDetails/EditDetails/<int:l_id>/',views.EditNoExpLanguageDetailView,name='Edit-NoExpLanguageDetails'),
    path('NoExperience/SocialMediaDetails/EditDetails/<int:sm_id>/',views.EditNoExpSocialMediaDetailView,name='Edit-NoExpSocialMediaDetails'),
    path('NoExperience/ActivityAchievementDetails/EditDetails/<int:aa_id>/',views.EditNoExpActivityAchievementDetailView,name='Edit-NoExpActivityAchievements'),
    path('NoExperience/SkillDetails/EditDetails/<int:sk_id>/',views.EditNoExpSkillDetailView,name='Edit-NoExpSkillDetails'),
    path('NoExperience/InterestDetails/EditDetails/<int:i_id>/',views.EditNoExpInterestDetailView,name='Edit-NoExpInterestDetails'),
    path('NoExperience/SoftSkillDetails/EditDetails/<int:ss_id>/',views.EditNoExpSoftSkillDetailView,name='Edit-NoExpSoftSkills'),
    path('NoExperience/StrengthWeaknessDetails/EditDetails/<int:sw_id>/',views.EditNoExpStrengthWeaknessDetailView,name='Edit-NoExpStrengthWeakness'),
    path('NoExperience/HobbieDetails/EditDetails/<int:h_id>/',views.EditNoExpHobbieDetailView,name='Edit-NoExpHobbies'),
    path('NoExperience/ProjectDetails/EditDetails/<int:p_id>/',views.EditNoExpProjectDetailView,name='Edit-NoExpProjects'),
    path('NoExperience/SummaryDetails/EditDetails/<int:s_id>/',views.EditNoExpSummaryDetailView,name='Edit-NoExpSummary'),
    path('NoExperience/TrainingDetails/EditDetails/<int:t_id>/',views.EditNoExpTrainingDetailView,name='Edit-NoExpTrainingDetails'),
    path('NoExperience/CertificationDetails/EditDetails/<int:c_id>/',views.EditNoExpCertificationDetailView,name='Edit-NoExpCertifications'),
    #################### EXP DEELETE PATHS ####################
    path('Experience/ContactDetails/DeleteDetails/<int:c_id>/',views.ExpDeleteContactDetailView,name='ExpDeleteContactDetails'),
    path('Experience/PersonalDetails/DeleteDetails/<int:p_id>/',views.ExpDeletePersonalDetailView,name='ExpDeletePersonalDetails'),
    path('Experience/EducationDetails/DeleteDetails/<int:e_id>/',views.ExpDeleteEducationDetailView,name='ExpDeleteEducationDetails'),
    path('Experience/LanguageDetails/DeleteDetails/<int:l_id>/',views.ExpDeleteLanguageDetailView,name='ExpDeleteLanguageDetails'),
    path('Experience/SocialMediaDetails/DeleteDetails/<int:sm_id>/',views.ExpDeleteSocialMediaDetailView,name='ExpDeleteSocialMediaDetails'),
    path('Experience/ActivityAchievementDetails/DeleteDetails/<int:aa_id>/',views.ExpDeleteActivityAchievementDetailView,name='ExpDeleteActivityAchievementDetails'),
    path('Experience/SkillDetails/DeleteDetails/<int:sd_id>/',views.ExpDeleteSkillDetailView,name='ExpDeleteSkillDetails'),
    path('Experience/SoftSkillDetails/DeleteDetails/<int:ss_id>/',views.ExpDeleteSoftSkillDetailView,name='ExpDeleteSoftSkillDetails'),
    path('Experience/InterestDetails/DeleteDetails/<int:i_id>/',views.ExpDeleteInterestDetailView,name='ExpDeleteInterestDetails'),
    path('Experience/StrengthWeakness/DeleteDetails/<int:sw_id>/',views.ExpDeleteStrengthWeaknessDetailView,name='ExpDeleteStrengthWeaknessDetails'),
    path('Experience/HobbieDetails/DeleteDetails/<int:h_id>/',views.ExpDeleteHobbieDetailView,name='ExpDeleteHobbieDetails'),
    path('Experience/ProjectDetails/DeleteDetails/<int:p_id>/',views.ExpDeleteProjectDetailView,name='ExpDeleteProjectDetails'),
    path('Experience/TrainingDetails/DeleteDetails/<int:t_id>/',views.ExpDeleteTrainingDetailView,name='ExpDeleteTrainingDetails'),
    path('Experience/CertificationDetails/DeleteDetails/<int:c_id>/',views.ExpDeleteCertificationDetailView,name='ExpDeleteCertificationDetails'),
    path('Experience/InternshipDetails/DeleteDetails/<int:in_id>/',views.ExpDeleteInternshipDetailView,name='ExpDeleteInternshipDetails'),
    path('Experience/ExperienceDetails/DeleteDetails/<int:e_id>/',views.ExpDeleteExperienceDetailView,name='ExpDeleteExperienceDetails'),
    path('Experience/SummaryDetais/DeleteDetails/<int:s_id>/',views.ExpDeleteSummaryDetailView,name='ExpDeleteSummaryDetails'),
    #################### NOEXP DEELETE PATHS ####################
    path('NoExperience/ContactDetails/DeleteDetails/<int:c_id>/',views.NoExpDeleteContactDetailView,name='NoExpDeleteContactDetails'),
    path('NoExperience/PersonalDetails/DeleteDetails/<int:p_id>/',views.NoExpDeletePersonalDetailView,name='NoExpDeletePersonalDetails'),
    path('NoExperience/EducationDetails/DeleteDetails/<int:e_id>/',views.NoExpDeleteEducationDetailView,name='NoExpDeleteEducationDetails'),
    path('NoExperience/LanguageDetails/DeleteDetails/<int:l_id>/',views.NoExpDeleteLanguageDetailView,name='NoExpDeleteLanguageDetails'),
    path('NoExperience/SocialMediaDetails/DeleteDetails/<int:sm_id>/',views.NoExpDeleteSocialMediaDetailView,name='NoExpDeleteSocialMediaDetails'),
    path('NoExperience/ActivityAchievementDetails/DeleteDetails/<int:aa_id>/',views.NoExpDeleteActivityAchievementDetailView,name='NoExpDeleteActivityAchievementDetails'),
    path('NoExperience/SkillDetails/DeleteDetails/<int:sd_id>/',views.NoExpDeleteSkillDetailView,name='NoExpDeleteSkillDetails'),
    path('NoExperience/SoftSkillDetails/DeleteDetails/<int:ss_id>/',views.NoExpDeleteSoftSkillDetailView,name='NoExpDeleteSoftSkillDetails'),
    path('NoExperience/InterestDetails/DeleteDetails/<int:i_id>/',views.NoExpDeleteInterestDetailView,name='NoExpDeleteInterestDetails'),
    path('NoExperience/StrengthWeakness/DeleteDetails/<int:sw_id>/',views.NoExpDeleteStrengthWeaknessDetailView,name='NoExpDeleteStrengthWeaknessDetails'),
    path('NoExperience/HobbieDetails/DeleteDetails/<int:h_id>/',views.NoExpDeleteHobbieDetailView,name='NoExpDeleteHobbieDetails'),
    path('NoExperience/ProjectDetails/DeleteDetails/<int:p_id>/',views.NoExpDeleteProjectDetailView,name='NoExpDeleteProjectDetails'),
    path('NoExperience/TrainingDetails/DeleteDetails/<int:t_id>/',views.NoExpDeleteTrainingDetailView,name='NoExpDeleteTrainingDetails'),
    path('NoExperience/CertificationDetails/DeleteDetails/<int:c_id>/',views.NoExpDeleteCertificationDetailView,name='NoExpDeleteCertificationDetails'),
    path('NoExperience/SummaryDetais/DeleteDetails/<int:s_id>/',views.NoExpDeleteSummaryDetailView,name='NoExpDeleteSummaryDetails'),

]

