# Generated by Django 3.2.5 on 2021-07-12 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(help_text='Enter your First Name', max_length=100)),
                ('Last_Name', models.CharField(help_text='Enter your Last Name', max_length=100)),
                ('Email_Id', models.EmailField(help_text='Enter your Email Id', max_length=100)),
                ('Mobile_No', models.CharField(help_text='Enter Your Mobile No', max_length=10)),
                ('Country', models.CharField(help_text='Enter Country Name', max_length=50)),
                ('State', models.CharField(help_text='Enter State Name', max_length=100)),
                ('City', models.CharField(help_text='Enter your City Name', max_length=80)),
                ('ZipCode', models.CharField(help_text='Enter your ZipCode', max_length=6)),
                ('Address', models.TextField(help_text='Enter your Address', max_length=800)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
