# Generated by Django 3.2.5 on 2021-07-12 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='default.jpg', upload_to='Photos/')),
                ('Experience', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('Internship', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('Gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=50)),
                ('DOB', models.DateField(help_text='Date Of Birth Details')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
