# Generated by Django 3.2.5 on 2021-07-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_auto_20210712_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='Address_2',
        ),
    ]
