# Generated by Django 3.2.5 on 2021-07-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_contactdetails_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='Address_2',
            field=models.CharField(default='India', help_text='Enter your Address', max_length=800),
        ),
    ]
