# Generated by Django 3.2.5 on 2021-07-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_contactdetails_address_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
