# Generated by Django 3.2.5 on 2021-07-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='Photo',
        ),
    ]
