# Generated by Django 3.2.5 on 2021-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_remove_personaldetails_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='Photo',
            field=models.ImageField(default='default.jpg', upload_to='Photos/'),
        ),
    ]
