# Generated by Django 3.2.5 on 2021-07-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_languagedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagedetails',
            old_name='Language_Confid',
            new_name='Language_Confidence',
        ),
    ]
