# Generated by Django 3.2.5 on 2021-07-12 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0014_rename_languages_languagedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMedia_Website_Name', models.CharField(help_text='Enter Social Media Website Name', max_length=100)),
                ('SocialMedia_Link', models.URLField(help_text='Enter Social Media Web Link', max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
