# Generated by Django 3.2.5 on 2021-07-12 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0015_socialmedialinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Training_Type', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], help_text='Enter Training Type', max_length=100)),
                ('Training_Country', models.CharField(blank=True, help_text='Enter your Training Country', max_length=300)),
                ('Training_State', models.CharField(blank=True, help_text='Enter Training State', max_length=200)),
                ('Training_City', models.CharField(blank=True, help_text='Enter your Training City', max_length=100)),
                ('Training_Org_Name', models.CharField(help_text='Enter Training organization Name', max_length=500)),
                ('Training_Course_Name', models.CharField(help_text='Enter Training Course', max_length=200)),
                ('Training_startDate', models.DateField(help_text='Training Start Date')),
                ('Training_EndDate', models.DateField(help_text='Training End Date')),
                ('Training_Description', models.TextField(help_text='Enter Training Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Position', models.CharField(help_text='enter your position', max_length=200)),
                ('About', models.CharField(help_text='About', max_length=350)),
                ('Summary', models.TextField(help_text='Your Information', max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrengthWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Strengths', models.TextField(help_text='Enter your Strengths', max_length=600)),
                ('Weakness', models.TextField(help_text='Enter your Weakness', max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soft_Skill_Name', models.CharField(help_text='Enter Soft Skill', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Name', models.CharField(help_text='Enter your Skill', max_length=300, unique=True)),
                ('Skill_Percentage', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(help_text='Enter Project Name', max_length=300)),
                ('Project_Url', models.URLField(help_text='Enter project Url', max_length=400)),
                ('Project_Description', models.TextField(help_text='Enter Project Description', max_length=800)),
                ('Project_Position', models.CharField(help_text='Enter your Position', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internship_choice', models.CharField(blank=True, choices=[('OFFLINE', 'OFFLINE'), ('PART TIME', 'PART TIME')], max_length=200)),
                ('Country', models.CharField(blank=True, help_text='Country Name', max_length=150)),
                ('State', models.CharField(blank=True, help_text='State Name', max_length=300)),
                ('City', models.CharField(blank=True, help_text='Enter City Name', max_length=300)),
                ('ZipCode', models.CharField(blank=True, help_text='Enter ZipCode', max_length=6)),
                ('Internship_Job_Type', models.CharField(blank=True, help_text='Experience Job Type', max_length=300)),
                ('Internship_Start_Date', models.DateField(blank=True, help_text='Enter Start Date')),
                ('Internship_End_Date', models.DateField(blank=True, help_text='Enter End Date')),
                ('Internship_Job_Description', models.TextField(blank=True, help_text='Enter Experience Description', max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_Names', models.CharField(help_text='Enter your Interests', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HobbieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbie', models.CharField(help_text='Enter your Hobbie', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience_choice', models.CharField(blank=True, choices=[('WORK FROM HOME', 'WORK FROM HOME'), ('PART TIME', 'PART TIME'), ('FULL TIME', 'FULL TIME')], max_length=200)),
                ('Country', models.CharField(blank=True, help_text='Country Name', max_length=150)),
                ('State', models.CharField(blank=True, help_text='State Name', max_length=300)),
                ('City', models.CharField(blank=True, help_text='Enter City Name', max_length=300)),
                ('ZipCode', models.CharField(blank=True, help_text='Enter ZipCode', max_length=6)),
                ('Experience_Job_Name', models.CharField(help_text='Enter Company Name', max_length=300)),
                ('Experience_Job_Type', models.CharField(blank=True, help_text='Experience Job Type', max_length=300)),
                ('Experience_Start_Date', models.DateField(blank=True, help_text='Enter Start Date')),
                ('Experience_End_Date', models.DateField(blank=True, help_text='Enter End Date')),
                ('Experience_Job_Description', models.TextField(blank=True, help_text='Enter Experience Description', max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_Type', models.CharField(choices=[('SCHOOL', 'SCHOOL'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('UNIVERSITY', 'UNIVERSITY'), ('HIGHER STUDIES', 'HIGHER STUDIES')], help_text='Organization Type', max_length=100)),
                ('Country_Name', models.CharField(help_text='Country Name', max_length=300)),
                ('State_Name', models.CharField(help_text='Enter State Name', max_length=300)),
                ('City_Name', models.CharField(help_text='City Name', max_length=150)),
                ('ZipCode', models.CharField(help_text='ZipCode', max_length=6)),
                ('Organization_Name', models.CharField(help_text='Organization Name', max_length=400)),
                ('Board_Of_Study', models.CharField(blank=True, help_text='Board Of Study', max_length=400)),
                ('Field_Of_Study', models.CharField(help_text='Enter your Field Study', max_length=400)),
                ('Standard', models.CharField(help_text='Your Standard', max_length=120)),
                ('Year_Passing', models.DateField(help_text='Year Passing')),
                ('Score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certification_Type', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], help_text='Enter Training Type', max_length=100)),
                ('Certify_Country', models.CharField(blank=True, help_text='Enter your Training Country', max_length=300)),
                ('Certify_State', models.CharField(blank=True, help_text='Enter Training State', max_length=200)),
                ('Certify_City', models.CharField(blank=True, help_text='Enter your Training City', max_length=100)),
                ('Certify_Org_Name', models.CharField(help_text='Enter Training organization Name', max_length=500)),
                ('Certify_Course_Name', models.CharField(help_text='Enter Training Course', max_length=200)),
                ('Certify_startDate', models.DateField(help_text='Training Start Date')),
                ('Certify_EndDate', models.DateField(help_text='Training End Date')),
                ('Certify_Description', models.TextField(help_text='Enter Training Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementsOrActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievement_Name', models.CharField(help_text='Enter Achievement Name', max_length=200)),
                ('Achievement_Description', models.CharField(help_text='Enter Achievement Description', max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
