# Generated by Django 3.2.5 on 2021-07-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0017_rename_org_type_educationdetails_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationdetails',
            name='Certify_ZipCode',
            field=models.CharField(blank=True, help_text='Enter ZipCode', max_length=100),
        ),
    ]
