# Generated by Django 3.2.5 on 2021-07-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0019_auto_20210713_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetails',
            old_name='Organization_Type',
            new_name='Org_Type',
        ),
    ]
