# Generated by Django 3.2.5 on 2021-07-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0020_rename_organization_type_educationdetails_org_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationdetails',
            old_name='Org_Type',
            new_name='Organization_Type',
        ),
    ]
