# Generated by Django 3.2.5 on 2021-07-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0021_rename_org_type_educationdetails_organization_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationDetails',
        ),
    ]
