# Generated by Django 3.2.5 on 2021-07-13 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0022_delete_educationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Type', models.CharField(choices=[('SCHOOL', 'SCHOOL'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('UNIVERSITY', 'UNIVERSITY'), ('HIGHER STUDIES', 'HIGHER STUDIES')], help_text='Organization Type', max_length=100)),
                ('Country_Name', models.CharField(help_text='Country Name', max_length=300)),
                ('State_Name', models.CharField(help_text='Enter State Name', max_length=300)),
                ('City_Name', models.CharField(help_text='City Name', max_length=150)),
                ('ZipCode', models.CharField(help_text='ZipCode', max_length=6)),
                ('Organization_Name', models.CharField(help_text='Organization Name', max_length=400)),
                ('Board_Of_Study', models.CharField(blank=True, help_text='Board Of Study', max_length=400)),
                ('Field_Of_Study', models.CharField(help_text='Enter your Field Study', max_length=400)),
                ('Standard', models.CharField(help_text='Your Standard', max_length=120)),
                ('Year_Passing', models.DateField(help_text='Year Passing')),
                ('Score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
