# Generated by Django 3.2.5 on 2021-07-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0023_educationdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softskills',
            old_name='Soft_Skill_Name',
            new_name='SoftSkill_Name',
        ),
    ]
