# Generated by Django 3.2.5 on 2021-07-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0024_rename_soft_skill_name_softskills_softskill_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchievementsOrActivities',
        ),
    ]
