# Generated by Django 3.2.5 on 2021-07-13 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0025_delete_achievementsoractivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsOrActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievement_Name', models.CharField(help_text='Enter Achievement Name', max_length=200)),
                ('Achievement_Description', models.CharField(help_text='Enter Achievement Description', max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
