# Generated by Django 3.2.5 on 2021-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0031_internshipdetails_internship_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarydetails',
            name='Summary',
            field=models.TextField(help_text='Your Information', max_length=1200),
        ),
    ]
