# Generated by Django 3.2.5 on 2021-08-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0039_alter_achievementsoractivities_actachiev_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementsoractivities',
            name='ActAchiev_Choice',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('ACHIEVEMENT', 'ACHIEVEMENT')], help_text='Choose Either Activity or Achievement', max_length=200),
        ),
    ]
